name: Deploy static content to Pages

on:
  push:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Independent job with no dependencies
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  # Job for running tests
  tests:
    runs-on: ubuntu-latest
 

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            ./cypress-visual-report/cypress-visual-report.html

  # Single deploy job that depends on "tests" job
  deploy:
    needs: [tests]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './cypress-visual-report/cypress-visual-report.html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
       
