name: Tests

on:
  push:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - run: npm ci

      - run: npm run test
     # Snapshot comparison disabled
        # env:
        #   VITE_CI_TEST: true
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ./cypress-visual-report/*
            ./cypress-visual-screenshots/*
          if-no-files-found: error
          retention-days: 7