name: Tests

on:
  push:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ matrix.node-version }}
          path: |
            ./cypress-visual-report/*
            ./cypress-visual-screenshots/*
          if-no-files-found: error
          retention-days: 7
